### ISSUE TITLE
'Report a map error' broken

### ISSUE THREAD

**Issue by gubuntu** [iwmihq/miniSASS#110]
<img width="515" alt="Screenshot 2022-09-29 at 11 46 56" src="https://user-images.githubusercontent.com/496911/192999566-bc5d278e-40c9-45ec-8d71-f99dddf6028c.png">

**Comment by NyakudyaA** [comment]
This also seems to be an issue with GFI which is only available for the minisass observations. They should be disabled for other layers or configure it against any layer

**Comment by gubuntu** [comment]
GFI?

**Comment by NyakudyaA** [comment]
GetFeatureInfo

**Comment by NyakudyaA** [comment]
Not needed anymore
