### ISSUE TITLE
Site data and graphs

### ISSUE THREAD

**Issue by NyakudyaA** [iwmihq/miniSASS#121]
# Problem
![image](https://github.com/kartoza/miniSASS/assets/2510900/476e84dd-2bec-4a01-867f-a900e3474df8)

Can we rather show the graphs at the bottom of the map or as a side panel when a user clicks on a site?

We also need to improve the graphs that are shown. Currently, no graph shows so we need to identify what kind of graphs were supposed to be shown before

**Comment by amyburness** [comment]
This needs to be a simple line chart of the change in average SASS Socre over time for the site. Note many sites have only one record so this plot will be one point on the chart. 
like this:
![image](https://github.com/kartoza/miniSASS/assets/77841514/fa5eca3c-82e3-4269-867b-dc9576fecfe1):
chart button:
![mdi_chart](https://github.com/kartoza/miniSASS/assets/77841514/d68c362c-a5eb-4006-a48b-1bc31c70fbcd)
chart eg:
![Chart](https://github.com/kartoza/miniSASS/assets/77841514/9bcca3af-6c2e-4ba0-9a8c-23ab44788f41)

**Comment by zamuzakki** [comment]
@amyburness If there are 2 data in 2022, will it be shown as average for 2022 (1 point), or show both (2 points)? Because the chart is on yearly basis.

**Comment by amyburness** [comment]
@zamuzakki can we make the chart based on the date of the record?

**Comment by zamuzakki** [comment]
@amyburness Yes.
These are how it looks like.
![1 data](https://github.com/kartoza/miniSASS/assets/7352963/b1ce6f38-97fd-4af1-beaf-474c578afd5d)
![2 dats](https://github.com/kartoza/miniSASS/assets/7352963/fe101cec-79a2-4df6-b8a7-9ee80a8920f8)
![Many datas](https://github.com/kartoza/miniSASS/assets/7352963/8f5cb547-d488-432b-99c1-f41f5a7b6b87)

The demo is in teh PR.

**Comment by amyburness** [comment]
@zamuzakki this looks great thanks.
