### ISSUE TITLE
Time series graphing, data interrogation & data download

### ISSUE THREAD

**Issue by sokolic** [iwmihq/miniSASS#13]
Add a data interrogation and time series graphing component. Allow users to download the data.

**Comment by sokolic** [comment]
This function has now been added although GroundTruth have requested that coloured bands representing the river health categories be added to the Score graph. Not sure if this is possible with ExtJS but will investigate.

**Comment by gubuntu** [comment]
Two comments:

Observations are not in date order in the graph here:

![screenshot from 2014-12-05 11 51 26](https://cloud.githubusercontent.com/assets/496911/5313813/3fa8749e-7c75-11e4-8784-9e3f2cc8b7fd.png)

Also, it would be nice to merge the graph and identify tools as the graph tool would add a data comparison tab and a graph tab to the identify data window, so all data visualisation would available in one action.
