### ISSUE TITLE
Review and update system architecture diagrams

### ISSUE THREAD

**Issue by amyburness** [iwmihq/miniSASS#132]
Please review and update the simple system architecture diagrams. 

Diagrams required:
1. Overall system architecture diagram (@NyakudyaA )
2. Data flow diagram (@NyakudyaA )
3. swimlane diagram ( @amyburness )

If we need to discuss this with the greater implementation team lets look at it.

**Comment by NyakudyaA** [comment]
This is complete and will be updated as we go along
