### ISSUE TITLE
Review map functionality

### ISSUE THREAD

**Issue by NyakudyaA** [iwmihq/miniSASS#133]
# Problem

The current architecture uses Openlayers 2 which is defined in the files in https://github.com/kartoza/miniSASS/tree/master/django_project/monitor/static/js, We need to analyze the function in the files `minisass.js` and  `minisass_map.js` to determine functionality matrix against other available tickets 

# Solution

Migration from Openlayers 2 to OpenLayers 8 is a big refactoring job, in some cases, it might be better to rewrite the logic using OL 8

At Kartoza we prefer to use https://maplibre.org/

@sokolic Are you comfortable using maplibre or do you see any advantages of maintaining OL. 

We need to make a choice urgently

**Comment by sokolic** [comment]
I have never used MapLibre so would need to learn how to use it. Given that Kartoza prefers MapLibre we might as well migrate to MapLibre, especially as the large jump from OL 2 to OL 8 would mean having to rewrite the code anyway.

**Comment by sokolic** [comment]
There are two main JavaScript files that were written for the original miniSASS website. Both apply to the map tab: **minisass_map.js** is loaded when users are not logged in while **minisass.js** is loaded when users are logged in and contains code for entering data, etc. These two files could be rolled into one as most (all?) of the code in minisass_map.js also appears in minisass.js.

Both these files contain **Open Layers** and a lot of **ExtJS** code so will need to be refactored.

**Comment by NyakudyaA** [comment]
Fixed in #204 @sokolic The basic structure of maplibre is now in place, Can we meet sometime next week on Tuesday to allocate some tickets to you?
