### ISSUE TITLE
Filter unverified observations

### ISSUE THREAD

**Issue by sokolic** [iwmihq/miniSASS#14]
Add a filter to display only unverified observations. This can be a filtering of observations when accessing them using QGIS/WFS or a filtering when using the Django site administration interface. Being able to filter will greatly speed up the process of verifying sites.

**Comment by gubuntu** [comment]
would this be for admin users only? How would they interact with this? Toggle between verified view and unverified view? In the main map page? (Have you used the WFS functionality in QGIS?)

**Comment by sokolic** [comment]
Perhaps this issue links partially to issue #12 (Data display interrogation/filtering enhancement) where I intend including an option for filtering by observation status. The user will be able to choose from one of All, Verified or Unverified, and these will be filtered against the flag field in the observation table. The filter form I'm designing looks something like this:
![filter_form](https://cloud.githubusercontent.com/assets/3035420/4732541/6b980f36-59bd-11e4-9d31-96797a2972d6.png)
This will filter the display of dirty/clean observations on the map. However, admin users will still have to toggle the flag from dirty to clean either by means of WFS or a Django view.

**Comment by sokolic** [comment]
Feedback from GroundTruth via email to Frank (29/10/2014):  _filter in backend (Home > Monitor > Observations) to display unverified observations only, to speed up verification process_

**Comment by ismailsunni** [comment]
Hi @sokolic 

I have made a filter in the django-admin by flag. And as bonus, I added two bulk actions to verify or un-verify some observations at once. See below:
![filtering by flag and bulk actions](https://cloud.githubusercontent.com/assets/1421861/4947536/8fd7b616-6625-11e4-96c9-4d778d1a7165.png)

What do you think?
