### ISSUE TITLE
Track deleted sites and observations

### ISSUE THREAD

**Issue by sokolic** [iwmihq/miniSASS#18]
Add a system for keeping track of deleted sites and observations. Keep all observations and sites in the database but flag them as deleted or perhaps move them to an archive table.

**Comment by ismailsunni** [comment]
Hi @sokolic ,
There are some question to confirm.

If a site is deleted and we should delete all observations in that site, right?

If we delete an observation and put it in archive table, should the deleted observation use site in the original site table or we create new site in archived_site table?

**Comment by sokolic** [comment]
1. Yes, if a site is deleted then the observations are also deleted.
2. If an observation is deleted, the site it is linked to is not necessarily deleted too. We'll therefore have some of the deleted observations linking to active sites and some to deleted sites. However, in the archived observations table we can't have the _site_ field linked to two different tables (i.e. active sites and deleted sites) at the same time so I think that in the model for the archived observations table we should change _site_ field from _models.ForeignKey_ to _models.IntegerField_.

**Comment by ismailsunni** [comment]
So, to sum up, we will save only the _gid_ of _site_ as _models.ForeignKey_ for ArchivedObservations table. But for ArvchivedTable, it will be the same. Am I right?

And lastly, since both of them has _user_ as foreignkey, we will delete the record that its user is deleted, right?

**Comment by sokolic** [comment]
Yes, save the _gid_ of _site_ in the ArchivedObservations tables but change the type to _models.IntegerField_

**Comment by sokolic** [comment]
I think do the same for the _user_ field in both the ArchivedSites and ArchivedObservations table: this becomes type _models.IntegerField_
