### ISSUE TITLE
Single line links at the bottom instead of multilined link

### ISSUE THREAD

**Issue by LunaAsefaw** [iwmihq/miniSASS#184]
The links: How to and Contact Us are on two lines on the footer of the landing page
![image](https://github.com/kartoza/miniSASS/assets/90245715/4b9c7bc4-1bdf-4cdc-9e63-731fc5219d93)

However, they are on a single line on the Figma board
![image](https://github.com/kartoza/miniSASS/assets/90245715/be7d440b-a0c7-44d9-b353-ebf8695adc8a)

**Comment by amyburness** [comment]
@tinashechiraya looks good 
![image](https://github.com/kartoza/miniSASS/assets/77841514/89937b5f-cf9d-45f1-a54b-9b3a59ce8398)
