### ISSUE TITLE
Gap between social media icons and text in the footer

### ISSUE THREAD

**Issue by LunaAsefaw** [iwmihq/miniSASS#185]
Current implementation:
![image](https://github.com/kartoza/miniSASS/assets/90245715/90600bd9-42b4-4711-8d63-c5b1e90bc44b)

Figma design:
![image](https://github.com/kartoza/miniSASS/assets/90245715/e91c7b3f-0200-4675-a4dd-dc2a6fe59527)
Keep the text as central (current implementation) but create some gap between the social media icons and the text

**Comment by NyakudyaA** [comment]
Seems like we missing the Downloads, Partners etc
![image](https://github.com/kartoza/miniSASS/assets/2510900/fc506c97-3320-4097-be5e-d4684ec8426b)

The HowTo link cycles back to the home page

**Comment by amyburness** [comment]
@tinashechiraya @NyakudyaA Downloads and Patnes are not needed anymore.
