### ISSUE TITLE
Almost all of the links on the 'How to' page work

### ISSUE THREAD

**Issue by LunaAsefaw** [iwmihq/miniSASS#187]
![image](https://github.com/kartoza/miniSASS/assets/90245715/7592d6f8-d77b-4cf8-a232-b98c9d786bef)
![image](https://github.com/kartoza/miniSASS/assets/90245715/eb14d520-0493-4e1d-9e0e-bf34957b9bbf)
![image](https://github.com/kartoza/miniSASS/assets/90245715/88775a42-b01f-4e96-8528-04b354b4be7f)
![image](https://github.com/kartoza/miniSASS/assets/90245715/38279d01-5065-4f1b-952a-a5f57120f0ec)
![image](https://github.com/kartoza/miniSASS/assets/90245715/10225f6d-8b6b-4c80-a40d-42208e09baad)
![image](https://github.com/kartoza/miniSASS/assets/90245715/069b13ea-c84e-4e48-a9e0-31d5752c3d92)

**Comment by amyburness** [comment]
@tinashechiraya 
this button should go to the section in the how-to on how to use the map and go to the map page. Let's rename the Button "Map Guide" 
![image](https://github.com/kartoza/miniSASS/assets/77841514/66df7325-8e29-4476-8a98-24344b106bfe)
And it should navigate here:
![image](https://github.com/kartoza/miniSASS/assets/77841514/c76d4068-95c6-425b-a9a1-450d45f11377)
