### ISSUE TITLE
Upload button should navigate to the map page then have the dialogue pop up

### ISSUE THREAD

**Issue by LunaAsefaw** [iwmihq/miniSASS#189]
![image](https://github.com/kartoza/miniSASS/assets/90245715/c786f7dd-e37a-4de7-9332-59bceb108f6f)

**Comment by amyburness** [comment]
@tinashechiraya This is not correct the Submit Results button needs to navigate to the map page with the data collection form open by default.

**Comment by amyburness** [comment]
![image](https://github.com/kartoza/miniSASS/assets/77841514/43ce4789-a06f-4180-8864-796758d8a4b4)
click on that button goes here:
![image](https://github.com/kartoza/miniSASS/assets/77841514/0aede968-ec28-4126-8da2-e646dcf32495)
