### ISSUE TITLE
Paragraph on the landing page

### ISSUE THREAD

**Issue by LunaAsefaw** [iwmihq/miniSASS#192]
Figma:
![image](https://github.com/kartoza/miniSASS/assets/90245715/3e50ee2b-8b29-4866-8f59-4ad43923f764)

The current design is not as spaced out as the figma design. Please put in spaces as indicated:
Current design:
![image](https://github.com/kartoza/miniSASS/assets/90245715/b039c197-6224-4ac2-98e7-10f719db20af)

Additionally, the Map link needs to navigate to the map page.

**Comment by amyburness** [comment]
@tinashechiraya looks good 
![image](https://github.com/kartoza/miniSASS/assets/77841514/08a25fa2-f59a-457e-bd9d-2370301f040c)
