### ISSUE TITLE
Fix alignment

### ISSUE THREAD

**Issue by LunaAsefaw** [iwmihq/miniSASS#193]
![image](https://github.com/kartoza/miniSASS/assets/90245715/080e146e-4762-4e5c-aba7-5a66c77df839)

Figma:
![image](https://github.com/kartoza/miniSASS/assets/90245715/8460fbad-613d-46b8-a425-92e9c12199d5)

**Comment by amyburness** [comment]
@tinashechiraya looks good 
![image](https://github.com/kartoza/miniSASS/assets/77841514/5107cb03-0ec6-43bf-922b-f3d06058ec10)
