### ISSUE TITLE
'Learn more' missing

### ISSUE THREAD

**Issue by LunaAsefaw** [iwmihq/miniSASS#194]
The learn more text is missing in the highlighted buttons below
![image](https://github.com/kartoza/miniSASS/assets/90245715/d0a154d1-da23-48ac-8d78-5563843c90a2)

Figma:
![image](https://github.com/kartoza/miniSASS/assets/90245715/871da9a0-0f1b-461d-be23-36eac5f90208)

**Comment by amyburness** [comment]
@tinashechiraya this looks done to me but the link still links to the old site we need to look at how the articles should look with the new site style at the rest of the site we may need to look at an article area in the admin site to administrate them. 
I will make a new ticket called Article Layout.
![image](https://github.com/kartoza/miniSASS/assets/77841514/b858eeb7-9c6d-4a9f-8760-f6673ab61f51)

**Comment by NyakudyaA** [comment]
Superseded by changes requested from email
