### ISSUE TITLE
Data form: Main form

### ISSUE THREAD

**Issue by LunaAsefaw** [iwmihq/miniSASS#196]
This is the main form that pops up
![image](https://github.com/kartoza/miniSASS/assets/90245715/d11e4fff-407c-4041-b73e-22148911a7d1)

However, this is the size restriction:
![image](https://github.com/kartoza/miniSASS/assets/90245715/8a6efcd3-cf21-4d49-b634-9429778daf5c)

But since it is scrollable, the first image contains the overall fields that will be seen if the user scrolls

**Comment by NyakudyaA** [comment]
This is completed
