### ISSUE TITLE
Data form: Process 1

### ISSUE THREAD

**Issue by LunaAsefaw** [iwmihq/miniSASS#197]
If select known site is selected, this is the form that needs to be displayed 
![image](https://github.com/kartoza/miniSASS/assets/90245715/71a0a1d1-fa8f-44eb-a78c-01064a6e1bc8)

**Comment by amyburness** [comment]
@tinashechiraya see review ticket #246

**Comment by NyakudyaA** [comment]
Superseeded by #347
