### ISSUE TITLE
Data form: process 2

### ISSUE THREAD

**Issue by LunaAsefaw** [iwmihq/miniSASS#198]
If select on map is selected, this is the form that will be displayed:
![image](https://github.com/kartoza/miniSASS/assets/90245715/7e250efb-8bd7-45ca-ad29-f21679a8f32b)

**Comment by LunaAsefaw** [comment]
This ticket is linked to #140

**Comment by amyburness** [comment]
@tinashechiraya see review ticket #246

**Comment by NyakudyaA** [comment]
Superseeded by #347
