### ISSUE TITLE
Data form: process 3

### ISSUE THREAD

**Issue by LunaAsefaw** [iwmihq/miniSASS#199]
If user select type in, this is the form:
![image](https://github.com/kartoza/miniSASS/assets/90245715/838f9eef-ea5a-447f-a138-6627e1b6f818)

The difference between this and process 2 is that the form design is the same but the field is auto-populated in process 2 when user clicks on the map while in process 3, the user inputs the data

**Comment by LunaAsefaw** [comment]
linked to #140

**Comment by amyburness** [comment]
@tinashechiraya see review ticket #246

**Comment by NyakudyaA** [comment]
This is superseded by #347
