### ISSUE TITLE
double-click zoom not centering map

### ISSUE THREAD

**Issue by gubuntu** [iwmihq/miniSASS#2]
I double click to zoom in and the map zooms in but pans down as well

**Comment by sokolic** [comment]
I wonder if this is because of the CMS header taking up space at the top of the screen. You might not be seeing the entire map and part of it is off the the bottom of the screen. As a result, when you think you are clicking in the middle of the map to zoom in, you are actually clicking in the top part of the map which then leads to the zooming/panning behaviour you describe.

**Comment by gubuntu** [comment]
I'm not sure - seems possible that it's a layout issue. Perhaps Jurgen would know. Not my area of expertise.

**Comment by sokolic** [comment]
There do seem to be conflicts between the CMS CSS and ExtJS CSS. You'll notice that the data input screen is now pegged to the top of the screen - this only happened after the map page was embedded in the CMS. I also can't drag the popup windows around any more.

**Comment by jurginius** [comment]
I am not getting this panning behaviour in Chrome on Linux. Any specific
browser giving this problem?

On Mon, May 27, 2013 at 10:47 AM, Frank Sokolic notifications@github.comwrote:

> There do seem to be conflicts between the CMS CSS and ExtJS CSS. You'll
> notice that the data input screen is now pegged to the top of the screen -
> this only happened after the map page was embedded in the CMS. I also can't
> drag the popup windows around any more.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sokolic/miniSASS/issues/2#issuecomment-18488535
> .

## 

Jurgen Blignaut
Software Creator
http://www.webtide.co.za
jurgen@webtide.co.za
+27829227239

**Comment by gubuntu** [comment]
mmm, now seems to be working OK in Chrome and Firefox on Ubuntu 12.10

On 27/05/2013 16:52, Jurgen Blignaut wrote:

> I am not getting this panning behaviour in Chrome on Linux. Any specific
> browser giving this problem?
> 
> On Mon, May 27, 2013 at 10:47 AM, Frank Sokolic 
> notifications@github.comwrote:
> 
> > There do seem to be conflicts between the CMS CSS and ExtJS CSS. You'll
> > notice that the data input screen is now pegged to the top of the 
> > screen -
> > this only happened after the map page was embedded in the CMS. I 
> > also can't
> > drag the popup windows around any more.
> > 
> > —
> > Reply to this email directly or view it on 
> > GitHubhttps://github.com/sokolic/miniSASS/issues/2#issuecomment-18488535
> > .
> 
> ## 
> 
> Jurgen Blignaut
> Software Creator
> http://www.webtide.co.za
> jurgen@webtide.co.za
> +27829227239
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/sokolic/miniSASS/issues/2#issuecomment-18502247.

## 

Gavin Fleming
t: 0218620670
w: 0218630660
c: 0845965680
f: 0866164820
Paarl
South Africa
18°59'19.6"E 33°44'46.1"S
