### ISSUE TITLE
Confirm entry of sites/observations

### ISSUE THREAD

**Issue by sokolic** [iwmihq/miniSASS#20]
Send a confirmation email to the user upon successful entry of a site and/or observation. The email should state that the observation will still be verified and that the person may be contacted in this regard. Another possiblility is to convey this information via a popup window instead of an email.

**Comment by gubuntu** [comment]
Develop and test Django view to populate and respond to popup?

**Comment by sokolic** [comment]
Perhaps the easiest way would be to do this via a popup in the map window. Currently, when a new observation is entered the values are POSTed and the map zooms to the new observation that has been entered. We could add a popup at this stage saying that the observation has been saved and is awaiting verification.

**Comment by sokolic** [comment]
I've added a popup that appears once an observation has been saved. Do you think it is necessary to also send an email?

**Comment by ismailsunni** [comment]
Should I implement the sending email after observation has been saved?

**Comment by sokolic** [comment]
Yes, would it be possible to trigger an email after the observation is saved?

**Comment by ismailsunni** [comment]
Hi @sokolic 
Yes, it's possible.

Btw, the email content that I write is:

```
Dear Ali Baba,

Thank you for your new observation submission.

Site Details:
River name: Progo River
Site name: Progo Site
Site Description: Progo is a river in Yogyakarta
Category: sandy


Observation Details:
Date: 02 Nov 2014
Collector's name: Ali Baba
Comments/notes: This is my third observation.

Kind regards,
The miniSASS team.
```

Is it ok?

**Comment by sokolic** [comment]
Could you also add the following at the bottom:
_Your observation still needs to be verified and you may contacted in this regard._

**Comment by ismailsunni** [comment]
Yes.

Not it becomes like this:

```
Dear Ali Baba,

Thank you for your new observation and site submission.

Site Details:
River name: Kapuas River
Site name: Site of Kapuas
Site Description: Kapuas is a river in Borneo island
Category: sandy

Observation Details:
Date: 01 Nov 2014
Collector's name: Ali Baba
Comments/notes: This is Comment.


Your observation still needs to be verified and you may contacted in this regard.

Kind regards,
The miniSASS team.
```

**Comment by sokolic** [comment]
Perfect.
