### ISSUE TITLE
Data form: manage images

### ISSUE THREAD

**Issue by LunaAsefaw** [iwmihq/miniSASS#202]
After user clicks on upload, that corresponding row changes to 'manage image' and when that is clicked, the form will show the uploaded image
![image](https://github.com/kartoza/miniSASS/assets/90245715/cbadb9c3-ee87-4915-a1d2-a0746e8b9f35)

**Comment by LunaAsefaw** [comment]
linked to #140

**Comment by NyakudyaA** [comment]
Implemented
