### ISSUE TITLE
Decrease space between video and text

### ISSUE THREAD

**Issue by LunaAsefaw** [iwmihq/miniSASS#211]
Current implementation:
![image](https://github.com/kartoza/miniSASS/assets/90245715/63efe890-46ed-4986-b932-fb1c8579b69b)

Figma:
![image](https://github.com/kartoza/miniSASS/assets/90245715/8a21ad35-62a8-4b75-8c55-b1e26f56391a)

**Comment by NyakudyaA** [comment]
Superseded bt the email from Nic
