### ISSUE TITLE
observation form updates

### ISSUE THREAD

**Issue by tinashechiraya** [iwmihq/miniSASS#230]
![Screenshot from 2023-11-18 15-27-23](https://github.com/kartoza/miniSASS/assets/2510900/32e9b236-2b10-4fce-9fa2-eea38edc5cb3)

- [x] Can we give tabs meaningful names

- [x] Will we show the actual image or a thumbnail which can be clicked and opens up? This should make the sidebar not long
@tinashechiraya since https://github.com/kartoza/miniSASS/pull/204 is merged and working. Can we have this PR include the changes currently in the main so that we can see how it looks?
for inspiration look at the side panel done by @dimasciput in [FBIS](https://freshwaterbiodiversity.org/map/#search/Arthropoda/taxon=&search=Arthropoda&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&module=occurrence&ecologicalCategory=&rank=&siteIdOpen=32504&ecosystemType=River,Wetland,Open%20waterbody,Unspecified)
- [x] add api endpoint to fetch the observation from the api
- [x] navigate to the observation location on the map
- [x] get observation images

**Comment by NyakudyaA** [comment]
Done
