### ISSUE TITLE
data input form validations

### ISSUE THREAD

**Issue by tinashechiraya** [iwmihq/miniSASS#234]
Can you add a gif that shows how Type coordinates work, I am worried that users might swap X and Y axis and have points rendering in the ocean or somewhere. What validation do we have to cater for that and when does the point being captured by the user show on the map. I think it might make sense to zoom to the site that has just been populated so that a user can see where they are especially for Typed coordinates

Also, I feel all panels should be on the other side below the blue navbar. @amyburness your thoughts

- [ ] validate form input fields 

@NyakudyaA so the record being captured here will be saved in the observations table/model in the db ?

**Comment by NyakudyaA** [comment]
superseded by validations
