### ISSUE TITLE
Email setup

### ISSUE THREAD

**Issue by tinashechiraya** [iwmihq/miniSASS#237]
This is the email service that will be used in the following scenarios:

- [x] contact us form
- [x] when user wants to reset their forgotten password
- [x] when user is activating their account after registration

@NyakudyaA is there any other use case?

**Comment by NyakudyaA** [comment]
Maybe when downloading data. If the data is too big and it will take time to prepare, we could send them an email with a link to download the data

**Comment by NyakudyaA** [comment]
This is done
