### ISSUE TITLE
Map interactions

### ISSUE THREAD

**Issue by tinashechiraya** [iwmihq/miniSASS#241]
These involve what the user can do on the map ,like on the old site

- [x] zoom to school or site
- [x] site data and graphs (click site on map ,select site from list)
- [x] observation details (when user clicks an observation on the map then it brings the side panel with details for the observation)
- [x] filter observations
- [x] click site / select site on map 

@NyakudyaA @amyburness are there any other interactions and anything else concerning the map

**Comment by amyburness** [comment]
@tinashechiraya We are not including schools anymore so only Zoom to site. 
we search for the site using the search bar on the top right

**Comment by NyakudyaA** [comment]
> These involve what the user can do on the map ,like on the old site
> 
>     * [ ]  zoom to school or site
The search bar allows users to zoom to an area or directly to a site.
> 
>     * [ ]  site data and graphs (click site on map ,select site from list)
If a user clicks on a site a side panel should show up with all the information about the site. On the side panel we should have an option to download data for that individual site. We should decide whether we automatically download all the data for sites that have multiple dates or we download the data on that active tab. If we choose the later we need a popup to indicate to the user that this is the behavior
> 
>     * [ ]  observation details (when user clicks an observation on the map then it brings the side panel with details for the observation)
Same as site data and graphs
> 
>     * [ ]  filter observations
Do you mean to allow users to visualize observations based on an area or some criteria. I would just let users only search and zoom to a specific site using the search bar.
> 
>     * [ ]  click site / select site on map
Same as other options above i.e site data
> 
> 
> @NyakudyaA @amyburness are there any other interactions and anything else concerning the map

**Comment by NyakudyaA** [comment]
Covered in other tickets being attended to
