### ISSUE TITLE
Additional fields on registration

### ISSUE THREAD

**Issue by tinashechiraya** [iwmihq/miniSASS#242]

**Comment by NyakudyaA** [comment]
![image](https://github.com/kartoza/miniSASS/assets/2510900/a7af61ed-f62f-4dd1-8644-be7b6276ab2d)

**Comment by NyakudyaA** [comment]
![image](https://github.com/kartoza/miniSASS/assets/2510900/feb2944d-6a49-4727-8eda-e61df9d81363)
