### ISSUE TITLE
Site UI improvements

### ISSUE THREAD

**Issue by amyburness** [iwmihq/miniSASS#245]
- [x] Move the socials links to under the login button
![image](https://github.com/kartoza/miniSASS/assets/77841514/05f3448f-47a3-4f3f-872a-aec6cf9f8dd9)
- [x] remove the pannel button
![image](https://github.com/kartoza/miniSASS/assets/77841514/fc99391c-99c9-475a-b2d0-d6363a38c911)

**Comment by NyakudyaA** [comment]
This is complete
![image](https://github.com/kartoza/miniSASS/assets/2510900/5f41fd71-49b9-4bf7-b883-28efef75e8b0)
