### ISSUE TITLE
Add video Liks to How To page 

### ISSUE THREAD

**Issue by amyburness** [iwmihq/miniSASS#247]
![image](https://github.com/kartoza/miniSASS/assets/77841514/c4e8bfcc-0204-4610-9d39-0595fdf0f2a0)

remove the miniSASS Newsletter and replace it with "miniSASS video guides"
 and add these links
 1-Introduction to miniSASS https://youtu.be/hRgO80-427w

2-Safety concerns for miniSASS https://youtu.be/yGbi7P8RYoU

3-What is in your miniSASS kit https://youtu.be/XJLcJMutXP8

4-What do you need to put together a miniSASS kit at home https://youtu.be/_-L-Xs4QJRg

5-Choosing your site for miniSASS https://youtu.be/WX_DkYyfnmk

6-how to take a sample https://youtu.be/XY_p8usHx4Q

7-Cleaning your sample https://youtu.be/8RATZXY2jyo

8-Using the dichotomous key https://youtu.be/hKdPiSSVL0s

9-How to calculate your score https://youtu.be/O_deXdCQIfM

10-Uploading your miniSASS score https://youtu.be/uUJTrkZKL6U

11-Using miniSASS for monitoring https://youtu.be/uU7hOj4zjG0

12-miniSASS in summary https://youtu.be/illWM9BhL-0

**Comment by NyakudyaA** [comment]
This has been revamped per the email sent on 19 December from Nic
