### ISSUE TITLE
Add hyperlinks to partner Logos

### ISSUE THREAD

**Issue by amyburness** [iwmihq/miniSASS#267]
Add hyperlinks to the partner logos on the site.

![image](https://github.com/kartoza/miniSASS/assets/77841514/639360e8-0995-4982-a3c2-35188d6eb70a)

Ground Truth- https://www.groundtruth.co.za
IWMI - https://www.iwmi.cgiar.org
Amazon - https://aws.amazon.com
CGIAR - https://www.cgiar.org
Unicef - https://www.unicef.org/

**Comment by NyakudyaA** [comment]
This is implemented
