### ISSUE TITLE
handle image uploads on the platfrom

### ISSUE THREAD

**Issue by NyakudyaA** [iwmihq/miniSASS#295]
# Problem

![Peek 2023-11-28 19-44](https://github.com/kartoza/miniSASS/assets/2510900/69ee5467-2971-47d0-b9a3-6a2447f03351)

Currently when adding images, nothing happens. It keeps looping over and over again

# solution

All uploaded images should be stored on the path `minio_images:/web` which is exposed inside the django and minio instance.
For each observation, we need to have a link for 1-M link for the images. So we need to either rename the images after they are uploaded on the platform and stored locally i.e User uploads an image called `foo.png` and it should be stored as `foo_some_random_value_${site_id}.png`

@LunaAsefaw We need a new table in the database that stores the path of the images and links them to the site

| site_id   | image_name |
| -------- | ------- |
| 1 | foo_bar_some_random_value_${site_id}.png    |
| 2 | foo_bar_some_random_value_${site_id}.png     |
| 3    | foo_bar_some_random_value_${site_id}.png    |

The idea is that in the mobile app users will upload images and they are pushed to the minio backend which we mount as a localfile system

**Comment by meomancer** [comment]
Hi @NyakudyaA @tinashechiraya 
Do we already have "Add Record" functions?
Because it is not working on my side

I think we need to finish the "Add Record" function before working on this ticket

And also, do we have feature to add image for current sites? I'm not sure where is it

**Comment by tinashechiraya** [comment]
@meomancer Alright I will add the add record today ... I'll update you when I'm done it shouldn't take too long

**Comment by dimasciput** [comment]
![Screenshot 2023-12-04 at 4 51 09 PM](https://github.com/kartoza/miniSASS/assets/1979569/e1d5cc36-ba97-41f3-bb43-82d46bb1da3b)

Please change the supported format to only image formats : JPEG,PNG

**Comment by meomancer** [comment]
As per discussion:
- [ ] Save image to /web/${BUCKET}/{observation_id}
- [ ] Site images is using site_photos
- [ ] Observation image is per species, using pest_photos
- [ ] Waiting @LunaAsefaw to update pest_photos that has relations between species_id, observation_id, and path_photo

**Comment by NyakudyaA** [comment]
Should this be moved to done @meomancer or you still need to do something else
