### ISSUE TITLE
blog not working?

### ISSUE THREAD

**Issue by gubuntu** [iwmihq/miniSASS#3]
does the blog need to be configured to set up content types? If I try to add a new blog all I can add are a title and slug, not form field for content.

**Comment by jurginius** [comment]
After capturing the title and slug, click on "Save and Continue Editing",
and you will be able to add snippet and body text plugins. There are other
problems with the blog plugin that I need to sort out, or get an updated or
different plugin for.

On Sat, May 25, 2013 at 4:41 PM, Gavin Fleming notifications@github.comwrote:

> does the blog need to be configured to set up content types? If I try to
> add a new blog all I can add are a title and slug, not form field for
> content.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sokolic/miniSASS/issues/3
> .

## 

Jurgen Blignaut
Software Creator
http://www.webtide.co.za
jurgen@webtide.co.za
+27829227239
