### ISSUE TITLE
Zero scores are legitimate

### ISSUE THREAD

**Issue by sokolic** [iwmihq/miniSASS#30]
Simon from GroundTruth mentioned in a recent email to me (29/10/2014) that zero scores are legitimate: _This was discussed previously - perhaps when we had no funding - and sorry I didn’t add to the wish list. There are legitimate observations in the database with a zero score, but display no icon. Could we please add a grey crab (attached, but you may already have) for a zero score (no inverts found). We would then have to add this to the legend. I will send through appropriate text  from team._
If we implement this it would require the following changes:
- [x] 1. Change the score_trigger in the db to return 0 and not NULL: **WHEN division_by_zero THEN NEW.score := 0; RETURN NEW;**
- [x] 2. Update the records in the observations table that have a NULL score
- [x] 3. Update _minisass_observations.sld_ to display a grey crab icon when score=0
- [x] 4. Update the geoserver template file _content.ftl_ to return a grey crab icon when score=0
- [x] 5. In _minisass.js_ update the _updateInputForm_ function to display a grey crab icon when score=0
- [x] 6. Update the map legend

**Comment by gubuntu** [comment]
I've done 1 and 2
minisass-cms=# update observations set score = 0 where score is null;
UPDATE 5

**Comment by gubuntu** [comment]
please do no 3. Admire

**Comment by gubuntu** [comment]
added clean and dirty grey crabs at every scale for score=0
