### ISSUE TITLE
Download Observation

### ISSUE THREAD

**Issue by tinashechiraya** [iwmihq/miniSASS#302]
- [x] modal pop with options to download as a csv or with images choices
- [x] download observation as csv
- [x] download observation with images

@NyakudyaA you can add more options that need to be available when downloading an observation here as per our last meeting

**Comment by NyakudyaA** [comment]
The modal popup should cover the following
* Format of records - It should either be CSV or geopackage
* Have an option/tickbox for the above formats to either include images or not
* Have an option to download a single observation per date or All observations for different dates

In future, we could include options like (But this should not be done now unless it intersects with this easily)
* Map interactions - Draw a bounding box or polygon using drawing tools to select a specific area and download those records within the AOI.

**Comment by zamuzakki** [comment]
@tinashechiraya @NyakudyaA When downloading as Geopackage, how should we represent the data? Let's say 2 observations belong to 1 site, the location would be same, making only 1 observation to be exported to GeoPackage.

**Comment by NyakudyaA** [comment]
> @tinashechiraya @NyakudyaA When downloading as Geopackage, how should we represent the data? Let's say 2 observations belong to 1 site, the location would be same, making only 1 observation to be exported to GeoPackage.

2 rows, each one indicating an observation

**Comment by zamuzakki** [comment]
@tinashechiraya @NyakudyaA image field is not yet added to the modal. @tinashechiraya told me we need to wait for @vermeulendivan or Ivan (maybe someone in the project that I don't know of) to implement the feature.

**Comment by NyakudyaA** [comment]
@zamuzakki Maybe have a quick chat with @meomancer who is implementing the upload images to understand this, So in theory during the download you need the following
* Download images for the site
* Download pest images if they exists for the observation
