### ISSUE TITLE
add sections to observation form

### ISSUE THREAD

**Issue by tinashechiraya** [iwmihq/miniSASS#303]
Description

like on fbis side bar panel there are sections some open by default . this will help to not make the form too long as we will need to add more things to the panel
Charts etc 

![sidebarPanel](https://github.com/kartoza/miniSASS/assets/70011086/108c18a7-58d6-4bcf-816d-6aef7821d8c6)

@NyakudyaA can you add more to the description here

**Comment by NyakudyaA** [comment]
Not valid anymore
