### ISSUE TITLE
Add a couple of options below logout

### ISSUE THREAD

**Issue by NyakudyaA** [iwmihq/miniSASS#326]
# Problem

When logged in I expect the user to be Able to update their info.

![image](https://github.com/kartoza/miniSASS/assets/2510900/9476bc1a-b6d6-42ba-bdb1-7ad7787a70f9)

# Solution

Something like the image below

![Screenshot from 2023-12-01 21-57-35](https://github.com/kartoza/miniSASS/assets/2510900/7e7a8807-47f6-49f8-89ec-98f280b875e8)

**Comment by amyburness** [comment]
@NyakudyaA @zamuzakki we likely need to add a user Icon to the nav bar where the user can access the menu @NyakudyaA mentioned
something like this:
![Frame 52](https://github.com/kartoza/miniSASS/assets/77841514/c57c48b3-0f81-49e6-85fb-27ed05b333f4)
with profile icon this:
![iconamoon_profile-circle-fill](https://github.com/kartoza/miniSASS/assets/77841514/a097784f-89a7-4215-acc1-f251bda3eb35)
