### ISSUE TITLE
Rethink Add Record Form

### ISSUE THREAD

**Issue by NyakudyaA** [iwmihq/miniSASS#347]
Currently, our form looks like the following

![image](https://github.com/kartoza/miniSASS/assets/2510900/3e55b93e-f787-4754-aa76-6d217c5ecb19)

This is an improvement but has some differences from the old site implementation

In the previous version, a user can either
* Choose an existing site
* Create a new site then add an observation.

Can we rather improve the form to cater for these cases?

# Possible Solutions
![Screenshot from 2023-12-05 15-14-05](https://github.com/kartoza/miniSASS/assets/2510900/2ab23d04-4719-4a8d-9f18-72187da4006f)

* Below the Data Input Form - Add a radio button that has options
## Add observation from an existing site

1) Allow a user to select a site or type and once selected zoom to the site and then we proceed to 
2) Populate the site details form with site information (This should not be editable) 
3) Disable coordinate capture. 
4) A user should be able to add more pictures about that site
5) The observation form should only be active/editable once option 2 has passed.

## Create New Site and Observation
1) Allow a user to capture site information(site name etc) and its images
2) Add a save button for the site information. On click of this you  should add a popup `Are you sure you want to save this site`
3) The save button/option to select a point on the map should be disabled and information about the site should be visible
4) The observation form should only be active/editable once option 3 has been completed

**Note** The solution above would eliminate choosing `Sites` in Site Location

@amyburness cc @tinashechiraya @LunaAsefaw What are your thoughts here?

**Comment by amyburness** [comment]
@tinashechiraya @NyakudyaA I think these can be included in the current form as we have it as follows with out adding an new site vs know site button as that function is there already. 

for a known site (with choosing on map)

![image](https://github.com/kartoza/miniSASS/assets/77841514/02ceaeaf-482c-40d0-981e-e0d547f422b4)
note the screenshot

**Comment by NyakudyaA** [comment]
@amyburness I think this is just a workaround and doesn't completely address the concerns.

1) When a user clicks on Add record, they do two things here. 
* Adding a new site or selecting from an existing site
* Populating an observation.
2) In cases where the site doesn't exist it needs to be created first then saved, and then an observation is linked to it.
 Remember in the DB there is a FK relationship between sites and observation hence the need to save the newly created site first before proceeding to add an observation otherwise the front end will need to save the information in that order to maintain the FK integrity.

In our current implementation, the Site Details always pop up regardless of you want to capture a new site. There is no way to let a user know that you can skip the site details if you choose an existing site.

I agree that the logic is kind of there but might need moving around
![Screenshot from 2023-12-06 16-56-14](https://github.com/kartoza/miniSASS/assets/2510900/f2ca6ee8-0c5b-4678-a5df-93f1d483da91)

1) In the above screenshot we move the site location below the site details. If a user chooses `Select known site` that additional field opens up and a user selects the site.
2) Populate the site info with the existing site details retrieved for that record. At this point, the details are read only.
3) A user can still add more site photos even if the site info is already saved.

If a user chooses `Select on Map` and Type in Coordinates we assume he is defining a new site. Then details in option 2 should be editable by the user and after capturing them he should be able to save them before proceeding to capture observations

**Note** We need an Info button on `Select on Map` and `Type in Coordinates` to indicate to the end user that these options are available for creating a new site.

@sokolic Can you give your input here, we need to refactor this before Friday

**Comment by LunaAsefaw** [comment]
@NyakudyaA I agree with this. The current model looks like this 
![image](https://github.com/kartoza/miniSASS/assets/90245715/6eac9431-a0eb-4efa-ad08-048a095b70e5)
This means that each observation record will reference which site it is taking place on there the insert statement would require a corresponding site_id eg insert into observations (gid, user_id, site_id..) values (1,1,5..) but if the user is creating a  site and an observation record at the same time (same form). The site table has site images and other attributes associated so adding it by just filling in this would not be ideal and this is suitable only when you are working with a site that already exists
![image](https://github.com/kartoza/miniSASS/assets/90245715/b2a1a20f-e601-4e80-a769-e2560868cec8)

The solution proposed [here](https://github.com/kartoza/miniSASS/issues/347#issue-2026211850) seems to eliminate these issues
