### ISSUE TITLE
Image uploads ui improvements

### ISSUE THREAD

**Issue by NyakudyaA** [iwmihq/miniSASS#373]
# Problem

![image](https://github.com/kartoza/miniSASS/assets/2510900/aa9d7096-a89b-4449-8175-963ce8d773ac)

- [x] `Select Selected Files` should be changed to `Upload chosen files`

- [x] After selecting an image I am unable to select multiple images again

![Peek 2023-12-07 17-40](https://github.com/kartoza/miniSASS/assets/2510900/f49bbe5e-c7ad-420a-844e-ccc752f0064e)

![image](https://github.com/kartoza/miniSASS/assets/2510900/88fc8bf0-11e4-4003-8654-d61891dfe1b8)

Should always be on the form to allow a user to select more images

- [x] After selecting an image and then uploading if you need to delete it, you manually have to click delete and choose `Select Selected files` which is not the best experience.

- [x] If you upload a lot of images at the same time the UI is not very nice i.e

![image](https://github.com/kartoza/miniSASS/assets/2510900/65d643a4-a4ce-4062-8cc8-f0c38d015317)

@meomancer some polishing up of the awesome work you did earlier

**Comment by zamuzakki** [comment]
Hi @NyakudyaA 
> After selecting an image and then uploading if you need to delete it, you manually have to click delete and choose Select Selected files which is not the best experience.

Do you want a button to clear all selected image?

> If you upload a lot of images at the same time the UI is not very nice i.e

Would aligning delete button solve the issue? Do you have any particular layout in mind?

**Comment by NyakudyaA** [comment]
> Hi @NyakudyaA 
> > After selecting an image and then uploading if you need to delete it, you manually have to click delete and choose Select Selected files which is not the best experience.
> 
> Do you want a button to clear all selected image?

Yes that will make sense but also once you have deleted the items I think closing the upload dialog should be all you need to do unlike the current implementation
> 
> > If you upload a lot of images at the same time the UI is not very nice i.e
> 
> Would aligning delete button solve the issue? Do you have any particular layout in mind?

I have no preference here, as long as it makes sense

**Comment by zamuzakki** [comment]
@NyakudyaA I've made PR for this ticket:
- [x] After selecting images, user is still able to add more images.
- [x] Add clear button to clear all selected images. When clicked, upload image modal is closed.
- [x] Align delete image button.
