### ISSUE TITLE
Bug on profile info page

### ISSUE THREAD

**Issue by NyakudyaA** [iwmihq/miniSASS#409]
![image](https://github.com/kartoza/miniSASS/assets/2510900/795384bf-2bd4-49d1-a771-0e3fc22c996a)

**Comment by zamuzakki** [comment]
@NyakudyaA Could you tell me which user you were using? When working on #391, I've tested the User Profile update functionality, and it worked. Here's the PR, it has been merged: https://github.com/kartoza/miniSASS/pull/399

**Comment by NyakudyaA** [comment]
@zamuzakki 
![Peek 2023-12-13 15-38](https://github.com/kartoza/miniSASS/assets/2510900/9c505a26-b49b-4e6f-824a-26fe3c9c128e)

**Comment by NyakudyaA** [comment]
This is fixed
