### ISSUE TITLE
changes to footer

### ISSUE THREAD

**Issue by gubuntu** [iwmihq/miniSASS#45]
I've altered copyright text and added a link to the github repo in base.html, (in kartoza/master). This should preferably be done via django admin / django cms?
I've also tried to remove the downloads and contact us links in the footer via django admin but doesn't seem to have any effect.

Please assist with both changes.

**Comment by ismailsunni** [comment]
hi @gubuntu 

> I've altered copyright text and added a link to the github repo in base.html, (in kartoza/master). This should preferably be done via django admin / django cms?

Not sure. I prefer to put in the base.html, since it contains the code-thing  And there is the `{% now "Y" %}` to show the year dynamically. It's much easier to put it in the code. I have tried to put in via django admin, but seems it's not obvious.

> I've also tried to remove the downloads and contact us links in the footer via django admin but doesn't seem to have any effect.

I just found that we need to click `publish draft` button to apply the changes.
![selection_019](https://cloud.githubusercontent.com/assets/1421861/5557792/b905af5c-8d3f-11e4-9cfe-dce716bdb151.png)

I don't have access to the admin page, so I can't help much.

**Comment by gubuntu** [comment]
On 26/12/2014 15:43, Ismail Sunni wrote:

> hi @gubuntu https://github.com/gubuntu
> 
> ```
> I've altered copyright text and added a link to the github repo in
> base.html, (in kartoza/master). This should preferably be done via
> django admin / django cms?
> ```
> 
> Not sure. I prefer to put in the base.html, since it contains the
> code-thing And there is the |{% now "Y" %}| to show the year
> dynamically. It's much easier to put it in the code. I have tried to
> put in via django admin, but seems it's not obvious.
> 
> ```
> I've also tried to remove the downloads and contact us links in
> the footer via django admin but doesn't seem to have any effect.
> ```
> 
> I just found that we need to click |publish draft| button to apply the
> changes.
> selection_019
> https://cloud.githubusercontent.com/assets/1421861/5557792/b905af5c-8d3f-11e4-9cfe-dce716bdb151.png
> 
> I don't have access to the admin page, so I can't help much.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sokolic/miniSASS/issues/45#issuecomment-68141579.
> 
> Ismail, please implement, I've made you an admin, will send details via
> email.

## 

---

Gavin Fleming PGP 1234
Visit http://kartoza.com http://kartoza.com/to find out about open source:
- Desktop GIS programming services
- Geospatial web development
- GIS Training
- Consulting Services
  Skype: phlemingo
  -------------------------------------------------------------------------------------------
  Kartoza = Linfiniti ∪ Afrispatial
