### ISSUE TITLE
observation styling and map extents

### ISSUE THREAD

**Issue by gubuntu** [iwmihq/miniSASS#5]
There was a request to symbolise observations with circles at very small scales. We'll add these on at the small end of the scales or just remove the maxdenominator limit from the smallest crabs, since we are now going out beyond SA. What you can do in OL to complement this is define maxExtent and restrictedExtent and / or a limited number of zoom levels or resolutions, so users can't pan or zoom outside southern Africa. These need to be defined in any case to allow zooming in closer that at present when the minisass base layer is on.

**Comment by sokolic** [comment]
This ties in with the "Home" button that Simon has asked me to add. I'll implement this as a "Zoom to Max Extent" function in js and hope to do it this week.
