### ISSUE TITLE
Troubleshoot 500 errors 

### ISSUE THREAD

**Issue by gubuntu** [iwmihq/miniSASS#54]
Gavin migrated the minisass site to a new server a few weeks ago but some Django urls are giving 500s. Please investigate and fix. Enable debugging if necessary. 

Server details at https://github.com/kartoza/kartoza/wiki/Server-miniSASS.

These are the known errors:
- [x] Clicking the link to the Contact Us page gives an error (http://minisass.org/en/contact-us/)
- [x] Submitting the contact form gives an error (but not sure if it sent the message)
- [x] Clicking the link to the How To page gives an error (http://minisass.org/en/how/)
- [x] Trying to register as a new user gives an error
- [x]  Adding an observation (by any method) results in an error message being displayed although the observation is actually saved
- [x] Saving a change through the admin interface (e.g. change an observation flag value) does commit the change, but returns an error page

**Comment by jurginius** [comment]
The contact us page requires a CMS plugin to display the contact form, as far as I remember. But the plugin should be a vanilla plugin. Its a CMS Page object, so should be relative straightforward.

The How To page is also just CMS Page objects, probably with images and links to documents. So should be relatively straightforward.

The regisration requires a Django Registration app that is an extension of django-registration. So, you need to make sure that the app is installed.

Both of these uses the Google Captcha service to validate human input. I think that is also a 3rd party app that is required. So, make sure all those are installed.

I have a suspicion that there is a pip requirements file that should specify all the correct dependencies.

More than that I can't recall.

I never worked on capturing observations.

**Comment by ismailsunni** [comment]
I tried to activate debug mode this morning. I found out that the problem is related
 to `decoder jpeg not available`. It's something related to PIL or Pillow.

I have tried some solution to fix that. But, still no lucks. I will look again later.

**Comment by jurginius** [comment]
You probably don't have libjpeg6-dev installed in your base Ubuntu OS. You
need to install that, and I think zlib1g-dev, then reinstall Pillow, and
you should be good.

On Thu, May 28, 2015 at 4:16 PM, Ismail Sunni notifications@github.com
wrote:

> I tried to activate debug mode this morning. I found out that the problem
> is related
> to decoder jpeg not available. It's something related to PIL or Pillow.
> 
> I have tried some solution to fix that. But, still no lucks. I will look
> again later.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sokolic/miniSASS/issues/54#issuecomment-106341205.

## 

Jurgen Blignaut
jurgen.blignaut@gmail.com
+27829227239

**Comment by gubuntu** [comment]
both these libs were installed. I uninstalled PIL (set to 1.1.7 in requirements.txt) and installed the current pillow version and that sorted out the first two issues but not the second two.

**Comment by ismailsunni** [comment]
For point 2 and 4, the smtp server is not setup yet. I have install postfix, no I got different error message.

```
SMTPRecipientsRefused at /en/accounts/register/
{'info@minisass.org': (550, '5.1.1 <info@minisass.org>: Recipient address rejected: User unknown in local recipient table')}
```

I will look at it again tomorrow morning.

**Comment by gubuntu** [comment]
I will check if port 25 is open and that the new server is on minisass.org whitelist. 

fyi, for your dev instance run this bash script in a terminal

```
#!/usr/bin/env bash
if [ -z $1 ]
then port=1025
else port=$1
fi
echo "Starting dumb mail server on localhost:$port"
python -m smtpd -n -c DebuggingServer localhost:$port
```

**Comment by ismailsunni** [comment]
hi @gubuntu 

It's still not working. I tried to send email, and it's got rejected when I saw the mail queue.

```
ismail@zagrh01gt01:~$ mailq
-Queue ID- --Size-- ----Arrival Time---- -Sender/Recipient-------
244C64005A4      323 Tue Jun  2 11:30:00  info@minisass.org
   (connect to alt2.aspmx.l.google.com[74.125.68.27]:25: Connection timed out)
                                         ismail@kartoza.com

```

Similar problem that I found, is http://serverfault.com/questions/595017/postfix-not-sending-mail. The accepted answer:
`Perhaps your ISP or server provider has closed outbound port 25 in their firewall? Contact your server provider and ask them what's going on.`

So, may be you can ask whether ISP or server provider, for SMTP server that we can use.

**Comment by gubuntu** [comment]
@ismailsunni I left you HC message re new email settings I put in settings.py. Host org won't open postfix and we should use the external SMTP rather than local postfix.

**Comment by gubuntu** [comment]
It's still giving 500s but taking longer to do so.

**Comment by ismailsunni** [comment]
May I use mailgun.com?
It's free for 300 emails/days for free account. Or if we verified our domain, it can send until 10.000 emails per month.

**Comment by gubuntu** [comment]
can you first figure out why mail.minisass.org is not working (see IP address in settings.py)? That is the one we are supposed to be using apparently

**Comment by gubuntu** [comment]
@ismailsunni I added EMAIL_USE_TLS = 'True' to settings.py but it's still giving 500s. What's debugging saying now?

**Comment by ismailsunni** [comment]
It gives different error:

```
gaierror at /en/contact-us/
[Errno -2] Name or service not known
Request Method: POST
Request URL:    http://minisass.org/en/contact-us/
Django Version: 1.4
Exception Type: gaierror
Exception Value:    
[Errno -2] Name or service not known
Exception Location: /usr/lib/python2.7/socket.py in create_connection, line 553
Python Executable:  /usr/bin/python
Python Version: 2.7.6
Python Path:    
['/home/minisass/python/lib/python2.7/site-packages',
 '/home/minisass/python/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg-info',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/home/minisass/miniSASS']
Server time:    Wed, 10 Jun 2015 04:54:50 +0200
```

Still debugging...

**Comment by gubuntu** [comment]
Thanks @ismailsunni for helping to debug. In the end it was mainly network settings in the hosting environment that were blocking emails, which in turn caused 90% of the errors. I have tested each case and it works perfectly and I've removed the error notice from the home page.

**Comment by ismailsunni** [comment]
Ah glad to hear that... That's why it's really hard to debug it.
