### ISSUE TITLE
Default map zoom extent and zoom to home page

### ISSUE THREAD

**Issue by NyakudyaA** [iwmihq/miniSASS#577]
# Problem

We currently default to zooming to the extent of South Africa

![image](https://github.com/kartoza/miniSASS/assets/2510900/a85b3ecc-44d2-433f-935a-09c183ae204d)

Since the site was originally centred on SA, it made sense to always zoom to SA but since we are going global can we not implement the following:

* If a user is geolocated from the browser let's zoom to the extent of his/her country even though there might be no points to show currently.
* Zoom to home -It also currently defaults to zooming to the extent of SA. Should we not zoom to the extent of all points/observations currently captured or maybe zoom to the extent of the country geolocated above.

@zamuzakki @tinashechiraya What's your take on this

**Comment by tinashechiraya** [comment]
@NyakudyaA I think it would be good to zoom in /centre the map where the  user is located ?

**Comment by zamuzakki** [comment]
@NyakudyaA @tinashechiraya I've made PR for this ticket.
