### ISSUE TITLE
Scrolling banner just under the menus

### ISSUE THREAD

**Issue by gubuntu** [iwmihq/miniSASS#59]
@sokolic has created a div for this so it needs some html/js/css to control it as well as a way to edit its content via Django admin or CMS admin. 

The client expects it to be in the header and thus appear on each page. 

This might not be the best design but the client has requested it.

**Comment by rischanlab** [comment]
Hi @gubuntu I am also not clear about this ticket, so is scrolling banner means image or just text?. 

thanks

**Comment by gubuntu** [comment]
It's the effect of text scrolling from right to left that you used to achieve with the html marquee element. That is deprecated, so I think the thing to use now is css animations. 

So an admin user must be able to manage the text content of that div and it must be styled so that it scrolls.

**Comment by gubuntu** [comment]
@rischanlab, master is deployed in production but layout has errors. Please diagnose and fix. 
Also, 
- please change the plain text plugin line in requirements.txt to 

```
cmsplugin-plaintext==0.1.1-alpha-2
```
- Even after running manage.py collectstatic, there are now two sets of big buttons at the top and the scrolling text doesn't work.

**Comment by rischanlab** [comment]
Hi @gubuntu I've deployed master branch from first in my new environments (using virtualenv). 
Marquee text is works. 
- First, I've add text in `News_ticker_content` 

![screen shot 2015-11-08 at 11 03 37 pm](https://cloud.githubusercontent.com/assets/2235894/11021235/ad24eec8-866d-11e5-8b0d-27d4749ebf7a.png)
- Save the changes. 
  ![screen shot 2015-11-08 at 11 03 45 pm](https://cloud.githubusercontent.com/assets/2235894/11021239/ba7b4d24-866d-11e5-8b43-ca5d2d76c559.png)
- The last did you `publish the draft`?. Previous I was forget to publish it. 

![screen shot 2015-11-08 at 11 03 59 pm](https://cloud.githubusercontent.com/assets/2235894/11021243/d0ea4b5a-866d-11e5-9f4d-9b1da9a85566.png)

Then for the `two sets of big buttons` which one do you mean? 
this is the view of header when I run in my pc

![screen shot 2015-11-08 at 11 02 11 pm](https://cloud.githubusercontent.com/assets/2235894/11021248/f53b5cec-866d-11e5-97ac-5f394c43807f.png)

**Comment by gubuntu** [comment]
@rischanlab please register yourself as a user at http://minisass.org. (You can check the registration process and see the country dropdown in action). Let me know when you've done that and I will make you an admin user. 

I have now added text (I forgot to save earlier and just hit Publish) but it is not scrolling. 

Re the extra logos, have a look at the site and see what I mean.

If I set you up as a user on the production server will you be happy to dig around in the deployed code and see where it's different to yours and find a fix?

**Comment by NyakudyaA** [comment]
Superseded by new design
