### ISSUE TITLE
Crab icons disappear

### ISSUE THREAD

**Issue by sokolic** [iwmihq/miniSASS#6]
Past a certain zoom the crab icons disappear.

Well, _some_ disappear

**Comment by sokolic** [comment]
Removing all these lines from the minisass_observations.sld on my local instance seems to resolve the problem: 
`<sld:MinScaleDenominator>10000</sld:MinScaleDenominator>`

**Comment by gubuntu** [comment]
I did this on the site but it does not appear to fix the problem. There's something causing only ''some'' of the icons to disappear, whereas ''all'' of them had that minScale set. I notice he purple ones disappearing close up. I'm handing over to Admire to investigate and see if he can identify the problem and fix.

**Comment by gubuntu** [comment]
fixed with https://github.com/kartoza/miniSASS/commit/289e0d9d183566fa43c456e1d7338af0e88e809e. Develop is deployed at present. Please test and close and merge into master and deploy.
