### ISSUE TITLE
add countries to registration dropdown

### ISSUE THREAD

**Issue by gubuntu** [iwmihq/miniSASS#60]
Add all countries to the registration drop-down list, with the most used countries appearing at the top of the list

**Comment by rischanlab** [comment]
Hi @gubuntu I am still not clear about this task,  I saw in this project, inside the fixtures you put the list of countries in initial_data.json, so should I put all of countries manually in that file? 

And also for the most used countries, in this project I saw that this project has feature that user can choose which countries that want to put in the top by modified the `rank`. So, I have to eliminate that feature?

**Comment by gubuntu** [comment]
@rischanlab, look in the minisass_registration app in the lookups model. 

Add all world countries to the model (using fixtures is a good idea; do you have world country data? just search for ISO country codes). Then confirm how the rank value is used and set the rank for the first, say, 5 countries and leave the other countries with rank unset. 

Here's the current ranking 

```
 Country | count
 South Africa |        396
 Other        |         17
 Lesotho      |          8
 Zimbabwe     |          7
 Namibia      |          5
 Swaziland    |          3
 DRC          |          3
 Tanzania     |          2
 Malawi       |          2
 Zambia       |          2
 Mozambique   |          1
 Botswana     |          1
```

from this query 

```
select l.description,count(l.description) country_id from minisass_registration_userprofile p join minisass_registration_lookup l on p.country_id = l.id group by l.description order by count(l.description) desc;
```

So the rank would be South Africa 1, Lesotho 2, etc.

**Comment by rischanlab** [comment]
Ok @gubuntu yes, I have it. I download from [here](http://peric.github.io/GetCountries/).
I've set the `rank` value to the most used countries.

Thanks

**Comment by gubuntu** [comment]
@rischanlab, I deployed master and ran manage.py loaddata on the fixture. You must have an older version of the database since some countries ended up with different ids and I had to fix them in the database. 

The ranking works but is preceded by a bunch of other countries. See what I mean by selecting a country in a user profile http://minisass.org/en/admin/minisass_registration/userprofile/.

**Comment by rischanlab** [comment]
Hi @gubuntu Yes I have the db but the old one. This is the db version that I have. 

![screen shot 2015-11-09 at 5 42 56 am](https://cloud.githubusercontent.com/assets/2235894/11023201/c9c63096-86a4-11e5-9f43-9794994385cc.png)

In this table, I was confused because it has two `Other` with different `id`.
From `South Africa` which is id = 9 to `Malawi` which is id = 17, I did not changed anything. 

So do I need to change the ids in `initial_data.json` if yes I think I need the newst db version. 
For the rank yes it weird, I'll check it.

**Comment by gubuntu** [comment]
@rischanlab you can delete initial_data.json as it is loaded in production now and I have fixed the ids in the database. 

The strange ranking behaviour does need attention however. (See it in action when you register yourself on the site)

**Comment by rischanlab** [comment]
Hi @gubuntu Please refer to this PR https://github.com/sokolic/miniSASS/pull/71

Thanks

**Comment by NyakudyaA** [comment]
This has been implemented
