### ISSUE TITLE
admin enhancements

### ISSUE THREAD

**Issue by gubuntu** [iwmihq/miniSASS#61]
In Django Admin, allow sites to be sorted. Also add sortable columns for user and river name. Also add a “show all” button

**Comment by rischanlab** [comment]
Hi @gubuntu could you help me, I am following [this step](https://github.com/sokolic/miniSASS/blob/master/INSTALL.md) but I got errors, some of columns missing. this is just an example when I click `Monitor-Sitess`

The error said that 
```
DatabaseError at /en/admin/monitor/sites/
column sites.the_geom does not exist
LINE 1: SELECT "sites"."gid", "sites"."the_geom", "sites"."site_name...
```
I've created the postgis extension in my db 
```
CREATE EXTENSION postgis;
CREATE EXTENSION postgis_topology;
```

I use postgress version 9.4 

than when I want to follow that manual, they said to download `Schools (mandatory)`
download from the GitHub miniSASS repository: webmapping/spatial_data/schools.*

but I cant find that directory.
