### ISSUE TITLE
Observations details page should be fixed width

### ISSUE THREAD

**Issue by NyakudyaA** [iwmihq/miniSASS#624]
![image](https://github.com/kartoza/miniSASS/assets/2510900/d05dcf19-72e3-4e97-a0a3-5d7347dc0fa5)

vs

![image](https://github.com/kartoza/miniSASS/assets/2510900/f7ace9a9-39d3-4230-8d75-d7b4dea26bd0)

It looks like as more observations are added per site, the panel is increasing in width

**Comment by LunaAsefaw** [comment]
@tinashechiraya new issue, seems like the data is now overlapping 
![image](https://github.com/kartoza/miniSASS/assets/90245715/4470d9e8-5c24-4d7a-8f65-8bb09d6d79d3)
