### ISSUE TITLE
Sites should be restricted to land areas only

### ISSUE THREAD

**Issue by NyakudyaA** [iwmihq/miniSASS#728]
# Problem

We need to allow users only to add observations for land areas.

# Solution

When a user chooses `Select on Map` or `Type in Coordinates`, we need a method to verify that the point lies within land masses.

* Add a new world boundary layer i.e Natural earth layer or OSM and buffer this layer slightly because boundaries in both these layers are either not that accurate
* Add a function that intersect on the point layer and gives a warning saying "Your points seem to be in the sea or not on land masses" 

@LunaAsefaw What are your thoughts?

**Comment by LunaAsefaw** [comment]
@NyakudyaA That is a great idea. And the intersection function would not be very taxing on the system either. For the coast, are we allowing a certain buffer around land masses or do we not allow any collection on coasts since they're not rivers?

**Comment by NyakudyaA** [comment]
@tinashechiraya I am thinking here that we could have the following
* Load a vector layer in the DB i.e admin_boundaries
* Create a spatial function in Postgres that returns a boolean value if a point intersects against the admin_boundaries i.e
```
SELECT point_intersects_admin(40.7128, -74.0060) AS intersects;
```
You pass lat, long values
* In the front end you pass the function to validate the lat/long if they intersect the polygon. If it doesn't we have an error "Your point seems to be outside the desired extent etc)

Otherwise, if there is a clever way to prevent users from clicking the oceans etc. Let me know your thoughts before I proceed

**Comment by zamuzakki** [comment]
@NyakudyaA I see @amyburness assigned this to me
![image](https://github.com/kartoza/miniSASS/assets/7352963/7f1b57e4-7cf6-48a9-ab19-c504902010f5)

So yes, I could create an endpoint to validate the location, which will use your function.

**Comment by NyakudyaA** [comment]
Added @zamuzakki
