### ISSUE TITLE
Pink tiles

### ISSUE THREAD

**Issue by sokolic** [iwmihq/miniSASS#8]
Map tiles come up as pink. Is this a server resource issue? Is it related to user connection speed?

**Comment by gubuntu** [comment]
Fixed key and duplicate issues with riverline layer as well as permission issue on hca5 layer and re-seeded GWC basemap cache. So far no pink tiles but if any appear now it probably is a resource issue.

**Comment by sokolic** [comment]
Haven't noticed any pink tiles for a while.
