### ISSUE TITLE
upgrade OS

### ISSUE THREAD

**Issue by gubuntu** [iwmihq/miniSASS#85]
migrate host to latest Ubuntu LTS with Livepatch enabled

SAIAB policy currently requires 18.04, not later

**Comment by PhatWheZ** [comment]
Policy must be updated as i'd prefer to use 20.04 LTS as the earliest release, or 22.04

**Comment by NyakudyaA** [comment]
@PhatWheZ When can you do the upgrade so that I can do the GeoServer docker install. Preferably we need to set up a staging env and get things working first

**Comment by PhatWheZ** [comment]
I am busy setting up a server internally for dev purposes, based on Ubuntu 20.04 LTS

**Comment by PhatWheZ** [comment]
Ubuntu 20.04 LTS server along with Docker and docker compose installed with root privileges provided to your user account. Details have been shared via email
