### ISSUE TITLE
Crab icons slow to appear

### ISSUE THREAD

**Issue by sokolic** [iwmihq/miniSASS#9]
Crab icons are slow to appear. Is this due ORASECOM server resources or slow user connection speed?

if they are slower than google layers then it is likely a server issue. If both are slow then bandwidth

**Comment by gubuntu** [comment]
I have added some optimisations to PostgreSQL config and added some indexes to sites and observations tables. Tomcat/Geoserver was already fairly well optimised. Crabs seem pretty responsive to me.
