### ISSUE TITLE
fix miniSASS mail

### ISSUE THREAD

**Issue by gubuntu** [iwmihq/miniSASS#92]
e.g. where does info@minisass.org go? (apparently to Groundtruth staff - please confirm)

confirm that mails from the site work. e.g. registration confirmation, observation confirmation etc. 

from Frank 7/12/21:
> try contacting ProSysCom ([www.prosyscom.co.za](http://www.prosyscom.co.za/)) as they seemed to be hosting the minisass email at one stage so probably also the domain. I remember chatting to Laven Kumarsamy from ISP support ([laven@prosyscom.co.za](mailto:laven@prosyscom.co.za)) to sort out an email password problem in February 2018.

**Comment by NyakudyaA** [comment]
This is now in use and all emails from the new site are coming from there
